import UI_TEXT from './ui-text.json';
const KEY='stadio-colors-v1', valid=c=>/^#[a-f0-9]{6}$/i.test(c);
function read(){try{const d=JSON.parse(localStorage.getItem(KEY)||'{}');return {recent:(d.recent||[]).filter(valid).slice(0,12),saved:(d.saved||[]).filter(valid).slice(0,24)};}catch{return {recent:[],saved:[]};}}
function write(d){try{localStorage.setItem(KEY,JSON.stringify(d));}catch{}}
export function rememberColor(color){if(!valid(color))return;const d=read();d.recent=[color,...d.recent.filter(c=>c!==color)].slice(0,12);write(d);}
function rgb(h,s,v){const f=n=>{const k=(n+h/60)%6;return Math.round(255*(v-v*s*Math.max(0,Math.min(k,4-k,1))));};return '#'+[f(5),f(3),f(1)].map(x=>x.toString(16).padStart(2,'0')).join('');}
function hsv(hex){const a=[1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)/255),m=Math.max(...a),n=Math.min(...a),d=m-n;let h=!d?0:m===a[0]?((a[1]-a[2])/d)%6:m===a[1]?(a[2]-a[0])/d+2:(a[0]-a[1])/d+4;return {h:(h*60+360)%360,s:m?d/m:0,v:m};}
export function createColorPicker({initial,onPreview,onFinish}){
 const T=UI_TEXT.colors,p=document.createElement('section');p.className='color-popover';p.role='dialog';p.ariaLabel=T.title;
 p.innerHTML='<strong></strong><canvas id="color-plane" width="248" height="144" tabindex="0"></canvas><label class="field"><span class="hue-label"></span><input id="color-hue" type="range" min="0" max="359"></label><div class="color-value"><span class="color-swatch"></span><input id="color-hex" aria-label="HEX" maxlength="7"></div><div class="color-sets"></div><div class="minirow"><button id="color-register"></button><button id="color-remove"></button></div><small class="color-hint"></small><div class="minirow"><button id="color-cancel"></button><button id="color-apply" class="primary"></button></div>';
 document.body.append(p);p.querySelector('strong').textContent=T.title;p.querySelector('.hue-label').textContent=T.hue;p.querySelector('.color-hint').textContent=T.hint;
 const q=s=>p.querySelector(s),canvas=q('canvas'),ctx=canvas.getContext('2d');canvas.ariaLabel=T.plane;
 let current=valid(initial)?initial:'#000000',state=hsv(current),dragging=false;
 function draw(){const {width:w,height:h}=canvas;ctx.fillStyle=rgb(state.h,1,1);ctx.fillRect(0,0,w,h);let g=ctx.createLinearGradient(0,0,w,0);g.addColorStop(0,'#fff');g.addColorStop(1,'#fff0');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,'#0000');g.addColorStop(1,'#000');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.beginPath();ctx.arc(state.s*w,(1-state.v)*h,5,0,2*Math.PI);ctx.lineWidth=2;ctx.strokeStyle='#fff';ctx.stroke();ctx.beginPath();ctx.arc(state.s*w,(1-state.v)*h,7,0,2*Math.PI);ctx.strokeStyle='#222';ctx.lineWidth=1;ctx.stroke();}
 function display(hex,keepHue=false){current=hex.toLowerCase();if(!keepHue)state=hsv(current);q('#color-hex').value=current;q('#color-hue').value=state.h;q('.color-swatch').style.background=current;draw();onPreview(current);q('#color-remove').disabled=!read().saved.includes(current);}
 function sets(){const host=q('.color-sets');host.replaceChildren();const d=read();for(const [name,colors]of [[T.set,['#ffffff','#222222','#d94141','#d5892f','#e7c842','#4a966c','#326cb6','#65509a','#d182a0','#624637','#c8edb7','#263a30']],[T.recent,d.recent],[T.saved,d.saved]]){const label=document.createElement('small');label.textContent=name;host.append(label);const row=document.createElement('div');row.className='color-chips';for(const color of colors){const b=document.createElement('button');b.style.background=color;b.title=b.ariaLabel=name+' '+color;b.dataset.color=color;b.onclick=()=>display(color);row.append(b);}if(!colors.length){const empty=document.createElement('span');empty.textContent=T.empty;row.append(empty);}host.append(row);}}
 function position(e){const r=canvas.getBoundingClientRect();state.s=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width));state.v=1-Math.max(0,Math.min(1,(e.clientY-r.top)/r.height));display(rgb(state.h,state.s,state.v),true);}
 canvas.onpointerdown=e=>{dragging=true;canvas.setPointerCapture(e.pointerId);position(e);};canvas.onpointermove=e=>{if(dragging)position(e);};canvas.onpointerup=e=>{dragging=false;canvas.releasePointerCapture(e.pointerId);};canvas.onpointercancel=()=>{dragging=false;onFinish(false);};
 canvas.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();state.s=Math.max(0,Math.min(1,state.s+(e.key==='ArrowRight'?.02:e.key==='ArrowLeft'?-.02:0)));state.v=Math.max(0,Math.min(1,state.v+(e.key==='ArrowUp'?.02:e.key==='ArrowDown'?-.02:0)));display(rgb(state.h,state.s,state.v),true);};
 q('#color-hue').oninput=e=>{state.h=+e.target.value;display(rgb(state.h,state.s,state.v),true);};q('#color-hex').oninput=e=>{if(valid(e.target.value))display(e.target.value);};
 for(const [id,label]of [['register','register'],['remove','remove'],['cancel','cancel'],['apply','apply']])q('#color-'+id).textContent=T[label];
 q('#color-register').onclick=()=>{const d=read();d.saved=[current,...d.saved.filter(c=>c!==current)].slice(0,24);write(d);sets();q('#color-remove').disabled=false;};q('#color-remove').onclick=()=>{const d=read();d.saved=d.saved.filter(c=>c!==current);write(d);sets();q('#color-remove').disabled=true;};
 q('#color-cancel').onclick=()=>onFinish(false);q('#color-apply').onclick=()=>onFinish(true);sets();display(current);return p;
}
