require('./local-test-env.cjs')();
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const { createHash } = require('node:crypto');
const { app, BrowserWindow, dialog } = require('electron');
const root = path.resolve(__dirname, '..');
const evidence = path.join(root, 'evidence');
const output = path.join(root, 'test-output', `app-flow-${Date.now()}`);
fs.mkdirSync(output, { recursive: true });
process.env.STADIO_USER_DATA = path.join(output, `profile-${Date.now()}`);
let saveTarget = null, openTargets = [];
dialog.showSaveDialog = async () => saveTarget ? { canceled: false, filePath: saveTarget } : { canceled: true };
dialog.showOpenDialog = async () => openTargets.length ? { canceled: false, filePaths: openTargets } : { canceled: true, filePaths: [] };
dialog.showErrorBox = (title, text) => { throw new Error(`${title}: ${text}`); };
const started = Date.now();
require('../desktop/main.cjs');
const delay = ms => new Promise(resolve=>setTimeout(resolve,ms));
const report = { started:new Date().toISOString(), output, checks:[], performance:{}, errors:[] };
let win;
const js = script => win.webContents.executeJavaScript(script, true);
const check = (name, value) => { assert.ok(value, name); report.checks.push(name); };
const fingerprint = bytes => createHash('sha256').update(bytes).digest('hex');
async function click(id) { await js(`document.getElementById(${JSON.stringify(id)}).click()`); await delay(80); }
async function waitUntil(script, timeout=12000) { const end=Date.now()+timeout; while(Date.now()<end){if(await js(script))return;await delay(25);}throw Error('Timed out: '+script); }
async function flow(){
  await app.whenReady();win=BrowserWindow.getAllWindows()[0];
  win.webContents.on('console-message', event=>{if(event.level==='error')report.errors.push(event.message);});
  if(win.webContents.isLoading())await new Promise(r=>win.webContents.once('did-finish-load',r));
  await waitUntil('!!window.__studio');
  report.performance.readyMs=Date.now()-started;
  check('startup blank document is clean',await js('!__studio.dirty && __studio.engine.layers.length===0'));
  await click('zoom-in');await click('fit');
  check('view changes never dirty the document',await js('!__studio.dirty'));
  await click('sample');await waitUntil('__studio.engine.layers.length===8');
  check('sample integrates raster, path, editable text',await js(`['image','path','textbox'].every(type=>__studio.engine.layers.some(o=>o.type.toLowerCase()===type))`));
  fs.writeFileSync(path.join(evidence,'sample-artwork.dake'),JSON.stringify(await js(`__studio.engine.serialize()`)));
  await js(`__studio.engine.canvas.discardActiveObject();__studio.engine.canvas.renderAll()`);
  const samplePng=await js(`__studio.engine.exportRaster('png',1)`);
  fs.writeFileSync(path.join(evidence,'sample-artwork.png'),Buffer.from(samplePng.split(',')[1],'base64'));
  fs.writeFileSync(path.join(output,'input.png'),Buffer.from(samplePng.split(',')[1],'base64'));
  await delay(150);fs.writeFileSync(path.join(evidence,'app-screen.png'),(await win.webContents.capturePage({x:0,y:0,width:1440,height:950},{stayHidden:true,stayAwake:true})).toPNG());
  const sourceBefore=fs.readFileSync(path.join(output,'input.png'));
  openTargets=[path.join(output,'input.png')];await click('import');await waitUntil('__studio.engine.layers.length===9');
  check('real PNG file imported through native bridge',await js(`__studio.engine.selected.type.toLowerCase()==='image'`));
  await js(`document.getElementById('adjust-brightness').value=18;document.getElementById('adjust-brightness').dispatchEvent(new Event('change'));`);
  await waitUntil(`__studio.engine.selected?.adjustments?.brightness===.18`);
  check('image adjustment UI changes persistent filter',await js(`__studio.engine.selected.filters.length>0`));
  await js(`__studio.engine.updateSelected({left:750,top:500,scaleX:.2,scaleY:.2});`);
  await js(`document.querySelector('[data-tool="rect"]').click()`);await delay(40);
  await js(`document.getElementById('prop-width').value=210;document.getElementById('prop-width').dispatchEvent(new Event('change'));`);await delay(40);
  check('numeric transform UI applies size',await js('Math.abs(__studio.engine.selected.getScaledWidth()-210)<.1'));
  await click('duplicate');check('duplicate UI adds editable layer',await js('__studio.engine.layers.length===11'));
  await click('undo');await waitUntil('__studio.engine.layers.length===10');await click('redo');await waitUntil('__studio.engine.layers.length===11');
  check('undo redo buttons restore object graph',true);
  saveTarget=path.join(output,'制作検証.dake');await click('save');await waitUntil('!__studio.dirty');
  check('native bridge writes project to chosen file',fs.existsSync(saveTarget));
  const savedFirst=fs.readFileSync(saveTarget,'utf8');
  await js(`__studio.engine.renameDocument('制作検証・再編集');`);await click('save');await waitUntil('!__studio.dirty');
  check('second save keeps exact previous file in .bak',fs.readFileSync(saveTarget+'.bak','utf8')===savedFirst);
  check('save clears obsolete crash recovery',!fs.existsSync(path.join(process.env.STADIO_USER_DATA,'recovery.json')));
  const savedData=JSON.parse(fs.readFileSync(saveTarget,'utf8'));
  check('project embeds pixels and vector paths',savedData.canvas.objects.some(o=>o.src?.startsWith('data:image/'))&&savedData.canvas.objects.some(o=>o.type.toLowerCase()==='path'));
  const savedRaster=await js(`__studio.engine.exportRaster('png',1)`);
  await js(`__studio.engine.newDocument({width:320,height:240,name:'temporary',background:'transparent'});`);
  openTargets=[path.join(output,'制作検証.dake')];await click('open');await waitUntil(`!!document.getElementById('dialog-discard')`);await click('dialog-discard');await waitUntil(`__studio.engine.name==='制作検証・再編集'&&!__studio.dirty`);
  check('saved project reopens through UI with layers',await js('__studio.engine.layers.length===11'));
  const reopenedRaster=await js(`__studio.engine.exportRaster('png',1)`);
  check('saved and reopened complex artwork exports byte-identical PNG pixels',savedRaster===reopenedRaster);
  const before=await js('JSON.stringify(__studio.engine.serialize())');
  fs.writeFileSync(path.join(output,'broken.dake'),'{broken');openTargets=[path.join(output,'broken.dake')];await click('open');await waitUntil(`!!document.getElementById('dialog-close')`);
  check('broken file reports error and preserves artwork',await js('JSON.stringify(__studio.engine.serialize())')===before);await click('dialog-close');
  for(const format of ['png','jpeg','webp','svg']){
    saveTarget=path.join(output,`export.${format==='jpeg'?'jpg':format}`);
    const begin=Date.now();await click('export');
    await js(`document.getElementById('export-format').value='${format}'`);await click('dialog-export');
    const end=Date.now()+10000;while(!fs.existsSync(saveTarget)&&Date.now()<end)await delay(30);
    check(`${format} export UI produces nonempty real file`,fs.statSync(saveTarget).size>100);
    report.performance[`${format}ExportMs`]=Date.now()-begin;
  }
  const png=fs.readFileSync(path.join(output,'export.png'));check('PNG export dimensions independent of viewport',png.readUInt32BE(16)===1200&&png.readUInt32BE(20)===800);
  const svg=fs.readFileSync(path.join(output,'export.svg'),'utf8');check('SVG export preserves path text embedded pixels',svg.includes('<path')&&svg.includes('<text')&&svg.includes('data:image/'));
  const svgSourceBefore=fs.readFileSync(path.join(output,'export.svg'));
  openTargets=[path.join(output,'export.svg')];await click('import');await waitUntil('__studio.engine.layers.length>11');
  check('exported SVG reimports to editable group',await js(`__studio.engine.selected.type.toLowerCase()==='group'`));
  saveTarget=path.join(output,'input.png');await click('export');await click('dialog-export');await waitUntil(`!!document.getElementById('dialog-close')`);
  check('export refuses to overwrite source image',fs.readFileSync(path.join(output,'input.png')).equals(sourceBefore));await click('dialog-close');
  report.sourceFingerprints={png:{before:fingerprint(sourceBefore),after:fingerprint(fs.readFileSync(path.join(output,'input.png')))},svg:{before:fingerprint(svgSourceBefore),after:fingerprint(fs.readFileSync(path.join(output,'export.svg')))}};
  check('all imported source file bytes remain unchanged',Object.values(report.sourceFingerprints).every(source=>source.before===source.after));
  await delay(2200);check('unsaved changes reach autosave on disk',fs.existsSync(path.join(process.env.STADIO_USER_DATA,'recovery.json')));
  const recovery=await js('window.stadio.getRecovery()');check('autosave roundtrip retains editable graph',recovery.data.canvas.objects.length===12);
  // Closing is an actual BrowserWindow close and must be cancelled in HTML.
  win.close();await waitUntil(`!!document.getElementById('dialog-cancel')`);await click('dialog-cancel');
  check('native close can be cancelled without losing artwork',!win.isDestroyed()&&await js('__studio.engine.layers.length===12'));
  report.expectedErrors=report.errors.filter(message=>message.includes("'stadio:openProject'")&&message.includes('対応するDAKE STADIO作品')||message.includes("'stadio:exportFile'")&&message.includes('元ファイルには上書き'));
  report.unexpectedErrors=report.errors.filter(message=>!report.expectedErrors.includes(message));
  check('no unexpected renderer errors',report.unexpectedErrors.length===0);
  report.passed=true;
  fs.writeFileSync(path.join(evidence,'app-flow-results.json'),JSON.stringify(report,null,2));
  fs.copyFileSync(path.join(output,'制作検証.dake'),path.join(evidence,'workflow-project.dake'));
  console.log(JSON.stringify(report,null,2));
  await js('window.stadio.closeReady()');await delay(100);app.exit(0);
}
flow().catch(error=>{report.passed=false;report.failure=error.stack;fs.writeFileSync(path.join(evidence,'app-flow-results.json'),JSON.stringify(report,null,2));console.error(error);app.exit(1);});
